services:
  rate-balancer:
    container_name: rate-balancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rateLimiter
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata-rb:/var/lib/postgresql/data
volumes:
  pgdata-rb:

